### ISSUE TITLE
Use plain composable instead vuex

### ISSUE THREAD

**Issue by levchak0910** [mutoe/vue3-realworld-example-app#15]
I would like to suggest to use plain composable functions instead vuex for a reason:  awful typescript support at the moment
What I don't really like that we don't have any type hints in IDE
Current _normal_ type checking is very wordy. Look closer to this repositories [1](https://github.com/flohop/vuex4-ts-boilerplate), [2](https://github.com/ux-engineer/using-vuex-4-modules-in-vue3-with-typescript/tree/master/src/store)

Based on @kiaking's[ topik](https://youtu.be/dQ5btkDrdJ8?t=878) I would like to use plain composables and after vuex v5 will be released, rewrite our store

@mutoe what do you think?

**Comment by mutoe** [comment]
I agree with you. Actually this small system isn't necessarily using Vuex (and Redux in React). I only added it because I wanted to use the Vuex in the Vue3 and see how it worked.

Turns out to be a little tricky, and does not support TypeScript well (including the current type declaration for props). 

I agree to use the modes Provider and Customer for state management, which is kind of like the Context in which React hooks are. It's important to note that this would be radical, but I support the point worth making. Go for it!

**Comment by mutoe** [comment]
Most of our system features has been completed, and I will work on the test next(cypress e2e test).

**Comment by levchak0910** [comment]
For e2e tests exist [this repo](https://github.com/cypress-io/cypress-example-conduit-app)
Maybe it will be easier to copypaste some tests)

**Comment by mutoe** [comment]
> For e2e tests exist [this repo](https://github.com/cypress-io/cypress-example-conduit-app)
> Maybe it will be easier to copypaste some tests)

Emm... Shocking! So Let me just copy it 😆

**Comment by levchak0910** [comment]
I found awesome state manager [Harlem](https://github.com/andrewcourtice/harlem) for vue 3 and decided to use it instead plain Composition API

**Comment by eshimischi** [comment]
Better option nowadays to use [Pinia](https://github.com/posva/pinia)

**Comment by mutoe** [comment]
> Better option nowadays to use [Pinia](https://github.com/posva/pinia)

Thanks for the reminder, will consider it in future :)
